// colors.ts
export const lightColors = {
  orageColor1: '#FF6101',
  white: 'fff',
  background: '#ffffff',
  headerBackground: '#f2f2f2',
  inputBackground: '#f0f0f0',
  text: '#333333',
  placeholderText: '#999999',
  sendButtonBackground: '#FF6101',
  border: '#dddddd',
  messageUserBackground: '#f1f1f1',
  messageAiBackground: '#fff',
  sectionHeader: '#333333',
  propertyName: '#333333',
  propertyPrice: '#555555',
  propertyDesc: '#666666',
  modalOverlay: 'rgba(0,0,0,0.5)',
  modalContentBackground: '#ffffff',
  closeButtonBackground: '#2089dc',
  closeButtonText: '#ffffff',
  mapButtonBackground: '#FF6101',
  mapIconColor: '#FF6101',
  sendIconColor: '#fff',
  propertyBorder: '#dddddd',
};

export const darkColors = {
  orageColor1: '#FF6101',
  white: 'fff',
  background: '#121212',
  headerBackground: '#1e1e1e',
  inputBackground: '#2c2c2c',
  text: '#ffffff',
  placeholderText: '#aaaaaa',
  sendButtonBackground: '#FF6101',
  border: '#333333',
  messageUserBackground: '#1f1f1f',
  messageAiBackground: '#2c2c2c',
  sectionHeader: '#ffffff',
  propertyName: '#ffffff',
  propertyPrice: '#cccccc',
  propertyDesc: '#bbbbbb',
  modalOverlay: 'rgba(0,0,0,0.5)',
  modalContentBackground: '#1f1f1f',
  closeButtonBackground: '#2089dc',
  closeButtonText: '#ffffff',
  mapButtonBackground: '#FF6101',
  mapIconColor: '#FF6101',
  sendIconColor: '#fff',
  propertyBorder: '#333333',
};